import {
  buildSignalBotMessage,
  type SignalBotNote,
} from "../services/signal-bot.js";
import { APP_URL, AS_OF, ID, market } from "./trading.js";

export function signalMessage() {
  const note: SignalBotNote = {
    id: ID,
    noteKey: "holder_research:v1:demo",
    title: "Demo: sharp YES interest",
    description: "A fictional holder increased their YES position.",
    rationale: "Static preview data.",
    producerRunId: "demo",
    direction: "up",
    confidence: 0.82,
    modelMeta: {
      external_research: {
        summary: "Demo research summary for Telegram presentation.",
      },
    },
    createdAt: AS_OF,
    revisionKind: "initial",
    meaningfulDeltaReasons: [],
    thesisKey: "holder_research:v2:polymarket:preview-market:YES",
    thesisRootNoteId: ID,
    primaryTargetMeta: { bucket: "sharp_side", side: "YES" },
    marketId: market.id,
    eventId: market.event_id,
    marketVenue: market.venue,
    marketTitle: market.title,
    marketSlug: null,
    marketDescription: null,
    eventTitle: market.event_title,
    eventDescription: null,
    outcomes: ["YES", "NO"],
    resolutionSource: null,
    marketSegment: null,
    closeTime: null,
    expirationTime: null,
    bestBid: 0.4,
    bestAsk: 0.42,
    lastPrice: 0.41,
    holderAddress: "0x0000000000000000000000000000000000000000",
    holderChain: "polygon",
    holderWalletId: "demo",
    holderOpenPnlUsd: 1500,
    holderPositionUsd: 12345,
    holderSide: "YES",
    holderActorMode: "single_holder",
    holderCredentialBullets: [
      "Up $2.5K over the last 30 days",
      "Won 65% of recent trades",
    ],
    holderClusterOpenPnlUsd: null,
    holderClusterPnl30dUsd: null,
    holderClusterSharpHolders: null,
    holderClusterSharpUsd: null,
    telegramMarketIdentityV1: {
      asOf: AS_OF,
      eventId: market.event_id,
      eventTitle: market.event_title,
      marketGroupItemTitle: market.title,
      marketId: market.id,
      marketQuestion: market.title,
      predicate: market.title,
      selectedSide: "YES",
      selectedSideLabel: "YES",
      source: "canonical_market",
      subject: "Demo rocket",
      venue: market.venue,
      version: 1,
    },
    signalPriceSnapshotV1: {
      asOf: AS_OF,
      displayPrice: 0.41,
      displayPriceSource: "midpoint",
      displaySide: "YES",
      marketId: market.id,
      NO: { ask: 0.6, bid: 0.58, mark: 0.59 },
      YES: { ask: 0.42, bid: 0.4, mark: 0.41 },
      venue: market.venue,
      version: 1,
    },
  };
  return buildSignalBotMessage({
    appBaseUrl: APP_URL,
    buyAmountUsd: 25,
    note,
    chatType: "channel",
    telegramMiniAppLinkBase: "https://t.me/preview_invalid_bot/demo",
  });
}
