import { tx, type Pool, type PoolClient } from "@hunch/infra";

import type {
  FundingDiscoveryRequest,
  FundingQuoteRequest,
  FundingDestinationOption,
  IntentLiquidityProjection,
  JsonObject,
  Money,
  SourceOption,
  SourceOptionLeg,
} from "../funding/domain/types.js";
import { fundingDiscoveryRequestSchema } from "../funding/domain/schemas.js";
import { isRawAmount } from "../funding/domain/raw-amount.js";
import {
  addUnsignedDecimals,
  compareUnsignedDecimals,
  formatUnsignedDecimal,
  multiplyUnsignedDecimals,
} from "../account-value/decimal.js";
import { rawAmount } from "../funding/planner/money.js";
import { fundingDestinationAmountForRequest } from "../funding/planner/trade-shortfall-amount.js";
import {
  fundingOwnedSourceIncludesLocation,
  fundingOwnedSourceReservationLocationId,
} from "../funding/planner/source-adapter.js";
import {
  FundingPlanningRuntime,
  type PreparedFundingRuntimeCommit,
} from "../funding/planner/runtime-service.js";
import { canonicalJsonHash } from "../funding/persistence/canonical.js";
import { fetchFundingConsumerReservationForUser } from "../funding/persistence/funding-evidence-repository.js";
import {
  commitTelegramAppHandoffWithExecution,
  resolveTelegramAppHandoff,
  type TelegramAppHandoff,
} from "./telegram-app-handoff.js";
import {
  isTelegramAppHandoffV2DirectTradeVenue,
  isTelegramAppHandoffV2TradeVenue,
  type TelegramAppHandoffV2TradeVenue,
} from "./telegram-app-handoff-v2-contract.js";

/**
 * Versioned Mini App contract, deliberately independent from the opaque th1_
 * token format. A v2 handoff carries a sealed funding *scope*, never calls,
 * signatures, provider quote references, or a funding consent token.
 */
export const TELEGRAM_APP_HANDOFF_V2_PLAN_VERSION = 2 as const;
export const TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION = 2 as const;

const SUPPORTED_CLIENT_ACTION_KINDS = new Set([
  "evm_transaction",
  "evm_transaction_batch",
  "svm_transaction",
  "external_handoff",
] as const);

export type TelegramAppHandoffFundingCapability =
  | Readonly<{ kind: "server_bot_exact" }>
  | Readonly<{
      kind: "web_funding_plan";
      requiredContractVersion: typeof TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION;
    }>
  | Readonly<{ kind: "external_deposit" }>
  | Readonly<{ kind: "unavailable"; reason: string }>;

type SourceDebitScope = Readonly<{
  asset: Money["asset"];
  /**
   * Reservation location for an owned route. A client handoff still retains
   * this identity: its action payload is adapter-owned, but it must not turn a
   * named wallet balance into an unscoped debit allowance.
   */
  locationId: string | null;
  /** Bounded source debit, expressed in the source asset's raw units. */
  maximumRaw: string;
  sourceFingerprint: string;
}>;

type DestinationScope = Readonly<{
  controllerWalletId: string;
  destinationOptionId: string;
  requiredAsset: Money["asset"];
  topology: string;
  venueBindingId: string;
  venueBindingOptionId: string;
  venueId: TelegramAppHandoffV2TradeVenue;
}>;

type TelegramAppHandoffV2FundingPlan = Readonly<{
  executionContractVersion: typeof TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION;
  /** Funding is client-executed only; server actions belong to bot exact flow. */
  funding: Readonly<{
    /** Generic FundingDiscoveryRequest, generated by the bot, never by web. */
    discoveryRequest: FundingDiscoveryRequest;
    destination: DestinationScope;
    fundingPolicyRevision: string;
    sourceDebits: readonly SourceDebitScope[];
  }>;
  kind: "funding";
  trade: JsonObject;
  version: typeof TELEGRAM_APP_HANDOFF_V2_PLAN_VERSION;
}>;

/**
 * A Buy that already has enough venue balance still needs a sealed handoff
 * when policy chooses Mini App execution. It deliberately has no fabricated
 * FundingOperation: the Mini App continues the exact bounded trade only.
 */
type TelegramAppHandoffV2DirectTradePlan = Readonly<{
  executionContractVersion: typeof TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION;
  kind: "direct_trade";
  trade: JsonObject;
  version: typeof TELEGRAM_APP_HANDOFF_V2_PLAN_VERSION;
}>;

export type TelegramAppHandoffV2Plan =
  | TelegramAppHandoffV2FundingPlan
  | TelegramAppHandoffV2DirectTradePlan;

export type MaterializedTelegramAppHandoffV2 = Readonly<{
  fundingOperationId: string;
  handoffId: string;
  kind: "client_execution_required";
  requiredContractVersion: typeof TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION;
}>;

/**
 * A ready generic operation has already persisted its exact consumer intent.
 * The Mini App passes this existing reservation to the ordinary venue trade
 * endpoint; that endpoint verifies the market/outcome and rejects any spend
 * above the reservation before it can submit an order.
 */
export type TelegramAppHandoffV2TradeContinuation = Readonly<{
  fundingOperationId: string;
  fundingReservationId: string;
  handoffId: string;
  kind: "trade_continuation_required";
  requiredContractVersion: typeof TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION;
}>;

/**
 * The ordinary web venue consumer has already accepted the reservation.  It
 * must not be handed back to the funding action loop: the linked generic
 * trade-attempt is now the durable authority for the venue submission.
 */
export type TelegramAppHandoffV2TradeInFlight = Readonly<{
  fundingOperationId: string;
  fundingReservationId: string;
  handoffId: string;
  kind: "trade_continuation_in_flight";
  requiredContractVersion: typeof TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION;
  tradeAttemptId: string;
  tradeAttemptState:
    | "accepted"
    | "ambiguous"
    | "claimed"
    | "submission_started";
}>;

/** A terminal trade intent is informational; it never authorizes another Buy. */
export type TelegramAppHandoffV2TradeTerminal = Readonly<{
  handoffId: string;
  kind: "trade_terminal";
  requiredContractVersion: typeof TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION;
  status: "cancelled" | "expired" | "failed" | "filled";
  tradeIntentId: string;
}>;

/** No funding exists for this handoff; the web consumer continues the sealed Buy. */
export type TelegramAppHandoffV2DirectTradeContinuation = Readonly<{
  handoffId: string;
  kind: "direct_trade_continuation_required";
  /** Pass unchanged to the ordinary web order endpoint with `handoffId`. */
  planFingerprint: string;
  requiredContractVersion: typeof TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION;
  tradeIntentId: string;
}>;

/** A direct order was claimed but has not reached a terminal venue result. */
export type TelegramAppHandoffV2DirectTradeInFlight = Readonly<{
  handoffId: string;
  kind: "direct_trade_in_flight";
  orderId: string | null;
  planFingerprint: string;
  requiredContractVersion: typeof TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION;
  tradeIntentId: string;
  venueOrderId: string | null;
}>;

export type TelegramAppHandoffV2Execution =
  | MaterializedTelegramAppHandoffV2
  | TelegramAppHandoffV2TradeContinuation
  | TelegramAppHandoffV2TradeInFlight
  | TelegramAppHandoffV2TradeTerminal
  | TelegramAppHandoffV2DirectTradeContinuation
  | TelegramAppHandoffV2DirectTradeInFlight;

/**
 * A returned in-flight or terminal state is observational only.  The caller
 * must not re-check live authority before showing it: that authority gates
 * the next action, not visibility into an action that was already claimed.
 */
export function isTelegramAppHandoffV2ReadOnlyExecution(
  execution: TelegramAppHandoffV2Execution,
): boolean {
  return (
    execution.kind === "direct_trade_in_flight" ||
    execution.kind === "trade_continuation_in_flight" ||
    execution.kind === "trade_terminal"
  );
}

export class TelegramAppHandoffV2Error extends Error {
  constructor(
    readonly code:
      | "contract_unsupported"
      | "destination_changed"
      | "funding_policy_changed"
      | "handoff_not_claimed"
      | "handoff_not_committed"
      | "plan_invalid"
      | "source_scope_changed"
      | "trade_intent_changed",
    message: string,
  ) {
    super(message);
    this.name = "TelegramAppHandoffV2Error";
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function isJsonObject(value: unknown): value is JsonObject {
  return isRecord(value);
}

function exactAsset(value: unknown): Money["asset"] | null {
  if (!isRecord(value)) return null;
  const { assetId, decimals, networkId } = value;
  return typeof assetId === "string" &&
    typeof networkId === "string" &&
    typeof decimals === "number" &&
    Number.isInteger(decimals) &&
    decimals >= 0 &&
    decimals <= 255
    ? { assetId, decimals, networkId }
    : null;
}

function exactMoney(value: unknown): Money | null {
  if (!isRecord(value)) return null;
  const asset = exactAsset(value.asset);
  return asset && isRawAmount(value.raw) ? { asset, raw: value.raw } : null;
}

function sameAsset(left: Money["asset"], right: Money["asset"]): boolean {
  return (
    left.networkId === right.networkId &&
    left.assetId.toLowerCase() === right.assetId.toLowerCase() &&
    left.decimals === right.decimals
  );
}

function actionShape(
  actions: readonly Readonly<{
    actor: "server" | "user";
    kind: string;
    valueMoving: boolean;
  }>[],
): readonly Readonly<{
  actor: "server" | "user";
  kind: string;
  valueMoving: boolean;
}>[] {
  return [...actions]
    .map((action) => ({
      actor: action.actor,
      kind: action.kind,
      valueMoving: action.valueMoving,
    }))
    .sort((left, right) =>
      `${left.kind}:${left.actor}:${left.valueMoving}`.localeCompare(
        `${right.kind}:${right.actor}:${right.valueMoving}`,
      ),
    );
}

function sourceIdentity(
  source: SourceOption["source"] | SourceOptionLeg["source"],
): JsonObject | null {
  if (source.kind === "owned_location") {
    return {
      asset: source.location.asset,
      locationId: source.location.locationId,
      kind: source.kind,
    };
  }
  if (source.kind === "external_ingress" && source.controlledSender) {
    return {
      asset: source.asset,
      ingressKind: source.ingressKind,
      kind: source.kind,
      networkId: source.networkId,
    };
  }
  return null;
}

function sourceScope(input: {
  actions: SourceOption["requiredActions"];
  amount: Money;
  maximumSourceDebitSlippageBps: number;
  source: SourceOption["source"] | SourceOptionLeg["source"];
}): SourceDebitScope | null {
  const identity = sourceIdentity(input.source);
  if (!identity) return null;
  const maximumRaw =
    (rawAmount(input.amount.raw) *
      BigInt(10_000 + input.maximumSourceDebitSlippageBps) +
      9_999n) /
    10_000n;
  return {
    asset: input.amount.asset,
    locationId:
      input.source.kind === "owned_location"
        ? input.source.location.locationId
        : null,
    maximumRaw: maximumRaw.toString(),
    sourceFingerprint: canonicalJsonHash({
      actions: actionShape(input.actions),
      source: identity,
    }),
  };
}

function quotedOptionSourceAmount(option: SourceOption): Money | null {
  const sourceAsset =
    option.source.kind === "owned_location"
      ? option.source.location.asset
      : option.source.kind === "external_ingress"
        ? option.source.asset
        : null;
  if (!sourceAsset) return null;
  const amount =
    option.quotedSourceAmount ??
    (option.maximumSourceRaw
      ? { asset: sourceAsset, raw: option.maximumSourceRaw }
      : null);
  return amount && sameAsset(amount.asset, sourceAsset) ? amount : null;
}

function optionSourceScopes(
  option: SourceOption,
  maximumSourceDebitSlippageBps = 0,
): readonly SourceDebitScope[] | null {
  if (option.source.kind === "composite") {
    const legs = option.sourceLegs;
    if (!legs || legs.length === 0) return null;
    const scopes = legs.map((leg) =>
      sourceScope({
        actions: leg.requiredActions,
        amount: leg.sourceAmount,
        maximumSourceDebitSlippageBps,
        source: leg.source,
      }),
    );
    return scopes.every((scope): scope is SourceDebitScope => scope != null)
      ? scopes
      : null;
  }
  const amount = quotedOptionSourceAmount(option);
  if (!amount) return null;
  // `maximumSourceRaw` is already a capacity boundary when an adapter has no
  // exact quote. Only a genuine quoted debit may move inside the confirmed
  // re-quote tolerance; inflating capacity would authorize unavailable funds.
  const quotedDebitSlippageBps = option.quotedSourceAmount
    ? maximumSourceDebitSlippageBps
    : 0;
  const scopes = [
    sourceScope({
      actions: option.requiredActions,
      amount,
      maximumSourceDebitSlippageBps: quotedDebitSlippageBps,
      source: option.source,
    }),
  ].filter((scope): scope is SourceDebitScope => scope != null);
  return scopes.length > 0 ? scopes : null;
}

function sourceScopeKey(scope: SourceDebitScope): string {
  return [
    scope.asset.networkId,
    scope.asset.assetId.toLowerCase(),
    String(scope.asset.decimals),
    scope.locationId ?? scope.sourceFingerprint,
  ].join(":");
}

/** A source may appear in more than one selectable route; its sealed cap is
 * the highest bound the bot explicitly permitted, never a sum of alternatives. */
function dedupeSourceScopes(
  scopes: readonly SourceDebitScope[],
): readonly SourceDebitScope[] {
  const bySource = new Map<string, SourceDebitScope>();
  for (const scope of scopes) {
    const key = sourceScopeKey(scope);
    const existing = bySource.get(key);
    if (
      !existing ||
      rawAmount(scope.maximumRaw) > rawAmount(existing.maximumRaw)
    ) {
      bySource.set(key, scope);
    }
  }
  return [...bySource.values()];
}

function hasUnsupportedClientAction(option: SourceOption): boolean {
  return option.requiredActions.some(
    (action) =>
      // V2 is a client execution contract. A generic plan carrying a server
      // action would need a second, implicit authority path, so reject it
      // rather than treating its kind as something the Mini App can execute.
      action.actor !== "user" ||
      action.kind === "signature" ||
      !SUPPORTED_CLIENT_ACTION_KINDS.has(
        action.kind as typeof SUPPORTED_CLIENT_ACTION_KINDS extends Set<infer T>
          ? T
          : never,
      ),
  );
}

function hasVenuePreparationSource(option: SourceOption): boolean {
  return (
    option.source.kind === "venue_preparation" ||
    option.sourceLegs?.some(
      (leg) => leg.source.kind === "venue_preparation",
    ) === true
  );
}

function isInteractiveExternalDeposit(option: SourceOption): boolean {
  return (
    option.source.kind === "external_ingress" && !option.source.controlledSender
  );
}

function sourceOptionFeeCapUsd(option: SourceOption): string | null {
  const fees = option.fees.map((fee) => fee.estimatedUsd);
  return fees.every((fee): fee is string => fee != null)
    ? addUnsignedDecimals(fees)
    : null;
}

function isSealableClientFundingOption(option: SourceOption): boolean {
  return (
    // A venue-preparation option owns several physical input reservations but
    // exposes no one client-debit identity. Do not seal it until its adapter
    // can provide the same exact locations a generic materialized plan uses.
    !hasVenuePreparationSource(option) &&
    !hasUnsupportedClientAction(option) &&
    !isInteractiveExternalDeposit(option) &&
    optionSourceScopes(option) != null &&
    sourceOptionFeeCapUsd(option) != null
  );
}

function maximumSealedFundingFeeUsd(
  options: readonly SourceOption[],
  maximumSlippageBps: number,
): string | null {
  let maximum: string | null = null;
  for (const option of options) {
    const cap = sourceOptionFeeCapUsd(option);
    if (cap == null) continue;
    if (maximum == null || compareUnsignedDecimals(cap, maximum) > 0) {
      maximum = cap;
    }
  }
  return maximum == null
    ? null
    : multiplyUnsignedDecimals(
        maximum,
        formatUnsignedDecimal(BigInt(10_000 + maximumSlippageBps), 4),
      );
}

function destinationScope(option: FundingDestinationOption): DestinationScope {
  if (!isTelegramAppHandoffV2TradeVenue(option.venueId)) {
    throw new TelegramAppHandoffV2Error(
      "destination_changed",
      "sealed handoff destination venue is unsupported",
    );
  }
  return {
    controllerWalletId: option.controllerWalletId,
    destinationOptionId: option.destinationOptionId,
    requiredAsset: option.requiredAsset,
    topology: option.topology,
    venueBindingId: option.venueBindingId,
    venueBindingOptionId: option.venueBindingOptionId,
    venueId: option.venueId,
  };
}

function sameDestinationScope(
  left: DestinationScope,
  right: FundingDestinationOption,
): boolean {
  return (
    left.controllerWalletId === right.controllerWalletId &&
    left.destinationOptionId === right.destinationOptionId &&
    left.topology === right.topology &&
    left.venueBindingId === right.venueBindingId &&
    left.venueBindingOptionId === right.venueBindingOptionId &&
    left.venueId === right.venueId &&
    sameAsset(left.requiredAsset, right.requiredAsset)
  );
}

/**
 * Capability is derived from a real generic projection, not from a venue or
 * chain boolean. `external_deposit` remains interactive: it must not be
 * advertised as an auto-close Mini App execution plan.
 */
export function resolveTelegramAppHandoffFundingCapability(input: {
  projection: IntentLiquidityProjection;
  serverBotExact: boolean;
}): TelegramAppHandoffFundingCapability {
  if (input.serverBotExact) return { kind: "server_bot_exact" };
  const options = input.projection.sourceOptions.filter(
    (option) => option.selectable,
  );
  if (options.some(isSealableClientFundingOption)) {
    return {
      kind: "web_funding_plan",
      requiredContractVersion:
        TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
    };
  }
  if (options.some(isInteractiveExternalDeposit)) {
    return { kind: "external_deposit" };
  }
  return { kind: "unavailable", reason: "no_supported_owned_source" };
}

/** Creates a sealed v2 plan from a server-produced generic liquidity result. */
export function buildTelegramAppHandoffV2Plan(input: {
  discoveryRequest: FundingDiscoveryRequest;
  fundingPolicyRevision: string;
  projection: IntentLiquidityProjection;
  trade: JsonObject;
}): TelegramAppHandoffV2FundingPlan {
  const destination = input.projection.destinationOptions.find(
    (option) =>
      option.selectable &&
      option.destinationOptionId === input.projection.destinationOptionId,
  );
  if (!destination) {
    throw new TelegramAppHandoffV2Error(
      "destination_changed",
      "sealed handoff lacks a selectable destination",
    );
  }
  const selectableSources = input.projection.sourceOptions.filter(
    (option) => option.selectable && isSealableClientFundingOption(option),
  );
  const maximumSlippageBps = input.discoveryRequest.maxSlippageBps ?? 0;
  const sourceDebits = dedupeSourceScopes(
    selectableSources.flatMap(
      (option) => optionSourceScopes(option, maximumSlippageBps) ?? [],
    ),
  );
  if (sourceDebits.length === 0) {
    throw new TelegramAppHandoffV2Error(
      "source_scope_changed",
      "sealed handoff lacks a supported owned source",
    );
  }
  const quotedFundingFeeCap = maximumSealedFundingFeeUsd(
    selectableSources,
    maximumSlippageBps,
  );
  if (quotedFundingFeeCap == null) {
    throw new TelegramAppHandoffV2Error(
      "source_scope_changed",
      "sealed handoff lacks an exact funding fee bound",
    );
  }
  const existingFeeCap = input.discoveryRequest.maxFeeUsd;
  const maxFeeUsd =
    existingFeeCap != null &&
    compareUnsignedDecimals(existingFeeCap, quotedFundingFeeCap) < 0
      ? existingFeeCap
      : quotedFundingFeeCap;
  const plan: TelegramAppHandoffV2Plan = {
    executionContractVersion:
      TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
    funding: {
      discoveryRequest: {
        ...input.discoveryRequest,
        maxFeeUsd,
      },
      destination: destinationScope(destination),
      fundingPolicyRevision: input.fundingPolicyRevision,
      sourceDebits,
    },
    kind: "funding",
    trade: input.trade,
    version: TELEGRAM_APP_HANDOFF_V2_PLAN_VERSION,
  };
  // Keep the producer and consumer contract identical: no caller can issue a
  // v2 token whose own materializer would later reject its sealed trade scope.
  return parseV2FundingPlan(plan);
}

/** Creates a sealed v2 handoff for one exact direct Buy or Sell. */
export function buildTelegramAppHandoffV2DirectTradePlan(input: {
  /** The verified controller which may submit this one sealed direct trade. */
  controllerWalletAddress: string;
  trade: JsonObject;
}): TelegramAppHandoffV2DirectTradePlan {
  const controllerWalletAddress = input.controllerWalletAddress.trim();
  if (!/^0x[0-9a-f]{40}$/iu.test(controllerWalletAddress)) {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed direct trade controller is malformed",
    );
  }
  const plan = parseV2Plan({
    executionContractVersion:
      TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
    kind: "direct_trade",
    trade: {
      ...input.trade,
      controllerWalletAddress: controllerWalletAddress.toLowerCase(),
    },
    version: TELEGRAM_APP_HANDOFF_V2_PLAN_VERSION,
  });
  if (plan.kind !== "direct_trade") {
    throw new Error("direct handoff builder returned a funding plan");
  }
  return plan;
}

function parseV2Plan(snapshot: JsonObject): TelegramAppHandoffV2Plan {
  if (
    snapshot.version !== TELEGRAM_APP_HANDOFF_V2_PLAN_VERSION ||
    snapshot.executionContractVersion !==
      TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION ||
    !isJsonObject(snapshot.trade) ||
    (snapshot.kind !== "funding" && snapshot.kind !== "direct_trade")
  ) {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed handoff is not execution-contract v2",
    );
  }
  const trade = snapshot.trade;
  const action = trade.action;
  if (
    (action !== "buy" && action !== "sell") ||
    !isTelegramAppHandoffV2TradeVenue(trade.venue) ||
    (trade.side !== "YES" && trade.side !== "NO") ||
    typeof trade.marketId !== "string" ||
    !trade.marketId ||
    typeof trade.outcomeTokenId !== "string" ||
    !trade.outcomeTokenId ||
    !(typeof trade.eventId === "string" || trade.eventId === null) ||
    typeof trade.maxSlippageBps !== "number" ||
    !Number.isInteger(trade.maxSlippageBps) ||
    trade.maxSlippageBps < 0
  ) {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed trade scope is malformed",
    );
  }
  if (
    (action === "buy" &&
      (typeof trade.amountUsd !== "number" ||
        !Number.isFinite(trade.amountUsd) ||
        trade.amountUsd <= 0 ||
        typeof trade.maxSpendUsd !== "number" ||
        !Number.isFinite(trade.maxSpendUsd) ||
        trade.maxSpendUsd < trade.amountUsd)) ||
    (action === "sell" &&
      (!isRawAmount(trade.sharesRaw) ||
        !isRawAmount(trade.minimumReceiveRaw) ||
        BigInt(trade.sharesRaw) <= 0n ||
        BigInt(trade.minimumReceiveRaw) <= 0n))
  ) {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed trade economic bounds are malformed",
    );
  }
  // A v2 handoff always names the one controller allowed to consume its
  // funding reservation or submit its direct Buy.  Funding and direct plans
  // use the same trade boundary; keeping it here prevents one from silently
  // becoming less constrained than the other.
  if (
    typeof trade.controllerWalletAddress !== "string" ||
    !/^0x[0-9a-f]{40}$/iu.test(trade.controllerWalletAddress)
  ) {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed trade controller is malformed",
    );
  }
  if (snapshot.kind === "direct_trade") {
    if (!isTelegramAppHandoffV2DirectTradeVenue(trade.venue)) {
      throw new TelegramAppHandoffV2Error(
        "plan_invalid",
        "sealed direct trade venue is unsupported",
      );
    }
    return {
      executionContractVersion:
        TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
      kind: "direct_trade",
      trade,
      version: TELEGRAM_APP_HANDOFF_V2_PLAN_VERSION,
    };
  }
  const funding = snapshot.funding;
  if (action !== "buy") {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed Sell cannot contain a funding plan",
    );
  }
  if (
    !isRecord(funding) ||
    !isJsonObject(funding.discoveryRequest) ||
    !isRecord(funding.destination) ||
    !Array.isArray(funding.sourceDebits) ||
    typeof funding.fundingPolicyRevision !== "string" ||
    !funding.fundingPolicyRevision
  ) {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed funding scope is malformed",
    );
  }
  const destinationAsset = exactAsset(funding.destination.requiredAsset);
  if (
    !destinationAsset ||
    typeof funding.destination.controllerWalletId !== "string" ||
    typeof funding.destination.destinationOptionId !== "string" ||
    typeof funding.destination.topology !== "string" ||
    typeof funding.destination.venueBindingId !== "string" ||
    typeof funding.destination.venueBindingOptionId !== "string" ||
    !isTelegramAppHandoffV2TradeVenue(funding.destination.venueId) ||
    funding.destination.venueId !== trade.venue
  ) {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed funding destination is malformed",
    );
  }
  const sourceDebits = funding.sourceDebits.map((value) => {
    if (!isRecord(value)) {
      throw new TelegramAppHandoffV2Error(
        "plan_invalid",
        "sealed funding source is malformed",
      );
    }
    const asset = exactAsset(value.asset);
    if (
      !asset ||
      !isRawAmount(value.maximumRaw) ||
      !(typeof value.locationId === "string" || value.locationId === null) ||
      typeof value.sourceFingerprint !== "string" ||
      !/^[0-9a-f]{64}$/iu.test(value.sourceFingerprint)
    ) {
      throw new TelegramAppHandoffV2Error(
        "plan_invalid",
        "sealed funding source is malformed",
      );
    }
    return {
      asset,
      locationId: value.locationId,
      maximumRaw: value.maximumRaw,
      sourceFingerprint: value.sourceFingerprint.toLowerCase(),
    };
  });
  if (sourceDebits.length === 0) {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed funding scope has no sources",
    );
  }
  const { serverAdditionalDestinationAmount, ...publicDiscoveryRequest } =
    funding.discoveryRequest;
  const additionalDestination =
    serverAdditionalDestinationAmount === undefined
      ? null
      : exactMoney(serverAdditionalDestinationAmount);
  const request = fundingDiscoveryRequestSchema.safeParse(
    publicDiscoveryRequest,
  );
  if (!request.success || request.data.purpose !== "trade_shortfall") {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed handoff may only materialize a client funding plan",
    );
  }
  if (
    serverAdditionalDestinationAmount !== undefined &&
    !additionalDestination
  ) {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed additional funding amount is malformed",
    );
  }
  return {
    executionContractVersion:
      TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
    funding: {
      discoveryRequest: {
        ...request.data,
        ...(additionalDestination
          ? { serverAdditionalDestinationAmount: additionalDestination }
          : {}),
      },
      destination: {
        controllerWalletId: funding.destination.controllerWalletId,
        destinationOptionId: funding.destination.destinationOptionId,
        requiredAsset: destinationAsset,
        topology: funding.destination.topology,
        venueBindingId: funding.destination.venueBindingId,
        venueBindingOptionId: funding.destination.venueBindingOptionId,
        venueId: funding.destination.venueId,
      },
      fundingPolicyRevision: funding.fundingPolicyRevision,
      sourceDebits,
    },
    kind: "funding",
    trade,
    version: TELEGRAM_APP_HANDOFF_V2_PLAN_VERSION,
  };
}

function parseV2FundingPlan(
  snapshot: JsonObject,
): TelegramAppHandoffV2FundingPlan {
  const plan = parseV2Plan(snapshot);
  if (plan.kind !== "funding") {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "this handoff has no funding plan",
    );
  }
  return plan;
}

function sealedTradeMatchesIntent(
  trade: JsonObject,
  intent: Readonly<{
    action: string;
    amount_usd: string | null;
    event_id: string | null;
    market_id: string;
    shares_raw?: string | null;
    side: string | null;
    venue: string;
  }>,
): boolean {
  const common =
    trade.action === intent.action &&
    trade.venue === intent.venue &&
    trade.marketId === intent.market_id &&
    trade.eventId === intent.event_id &&
    trade.side === intent.side;
  if (!common) return false;
  if (trade.action === "sell") {
    return (
      typeof trade.sharesRaw === "string" &&
      intent.shares_raw != null &&
      trade.sharesRaw === intent.shares_raw
    );
  }
  const sealedAmount = trade.amountUsd;
  return (
    typeof sealedAmount === "number" &&
    Number.isFinite(sealedAmount) &&
    intent.amount_usd != null &&
    Number(intent.amount_usd) === sealedAmount
  );
}

export function isTelegramAppHandoffV2Plan(snapshot: JsonObject): boolean {
  try {
    parseV2Plan(snapshot);
    return true;
  } catch {
    return false;
  }
}

/**
 * Select the parser from the declared execution-contract generation, not from
 * whether the v2 body happens to parse. A malformed v2 object must fail closed
 * rather than be interpreted as the old callback-replay handoff.
 */
export function telegramAppHandoffPlanGeneration(
  snapshot: JsonObject,
): "legacy" | "unsupported" | "v2" {
  if (snapshot.version === TELEGRAM_APP_HANDOFF_V2_PLAN_VERSION) return "v2";
  return snapshot.version == null || snapshot.version === 1
    ? "legacy"
    : "unsupported";
}

export function parseTelegramAppHandoffV2Plan(
  snapshot: JsonObject,
): TelegramAppHandoffV2Plan {
  return parseV2Plan(snapshot);
}

/**
 * A v2 handoff scopes an owned source by its stable reservation location and
 * exact asset.  Old snapshots included the then-current action shape in their
 * fingerprint, so matching that field would turn a harmless fresh-plan setup
 * change into a false `source_scope_changed`.  Null-location ingress remains
 * fingerprint-bound because it has no durable reservation location.
 */
export function telegramAppHandoffV2SourceOptionWithinScope(
  sealed: readonly SourceDebitScope[],
  option: SourceOption,
): boolean {
  const current = optionSourceScopes(option);
  if (!current || current.length === 0) return false;
  return current.every((entry) =>
    sealed.some((candidate) => {
      if (!sameAsset(candidate.asset, entry.asset)) return false;
      if (candidate.locationId !== null || entry.locationId !== null) {
        return (
          candidate.locationId !== null &&
          entry.locationId !== null &&
          candidate.locationId === entry.locationId
        );
      }
      return candidate.sourceFingerprint === entry.sourceFingerprint;
    }),
  );
}

type PreparedOwnedSource = Readonly<{
  kind: "owned_location";
  location: Readonly<{
    asset: Money["asset"];
    details: Readonly<Record<string, unknown>>;
    locationId: string;
  }>;
}>;

function preparedOwnedSource(value: unknown): PreparedOwnedSource | null {
  if (!isRecord(value) || value.kind !== "owned_location") return null;
  const location = isRecord(value.location) ? value.location : null;
  const asset = location ? exactAsset(location.asset) : null;
  const details =
    location && isRecord(location.details) ? location.details : null;
  return location && asset && details && typeof location.locationId === "string"
    ? {
        kind: "owned_location",
        location: { asset, details, locationId: location.locationId },
      }
    : null;
}

function preparedOwnedSources(
  value: unknown,
): readonly PreparedOwnedSource[] | null {
  if (!isRecord(value) || !isRecord(value.source)) return null;
  const composite = value.kind === "composite";
  const compositeSource = value.source.kind === "composite";
  const legs = Array.isArray(value.sourceLegs) ? value.sourceLegs : null;
  if (composite || compositeSource || legs) {
    if (
      !composite ||
      !compositeSource ||
      !legs ||
      !Number.isInteger(value.source.legCount) ||
      value.source.legCount !== legs.length
    ) {
      return null;
    }
    const owned: PreparedOwnedSource[] = [];
    for (const leg of legs) {
      if (!isRecord(leg) || !isRecord(leg.source)) return null;
      if (leg.source.kind === "owned_location") {
        const source = preparedOwnedSource(leg.source);
        if (!source) return null;
        owned.push(source);
      } else if (
        leg.source.kind !== "external_ingress" &&
        leg.source.kind !== "venue_preparation"
      ) {
        return null;
      }
    }
    return owned;
  }
  if (value.source.kind === "owned_location") {
    const source = preparedOwnedSource(value.source);
    return source ? [source] : null;
  }
  return value.source.kind === "external_ingress" ||
    value.source.kind === "venue_preparation"
    ? []
    : null;
}

function preparedOwnedSourceKey(
  asset: Money["asset"],
  reservationLocationId: string,
): string {
  return [
    asset.networkId,
    asset.assetId.toLowerCase(),
    String(asset.decimals),
    reservationLocationId,
  ].join(":");
}

function preparedPlanWithinSourceScope(
  input: Readonly<{
    prepared: PreparedFundingRuntimeCommit;
    sealedSources: readonly SourceDebitScope[];
  }>,
): boolean {
  const reservations = input.prepared.operation.quote.planSnapshot.reservations;
  const debits = reservations.filter(
    (reservation) => reservation.mode === "subtract_available",
  );
  if (debits.length === 0) {
    const operation = input.prepared.operation.quote.planSnapshot.operation;
    const requested = operation.requestedSourceAmount;
    const requestedAsset =
      requested && isRecord(requested) ? exactAsset(requested.asset) : null;
    const requestedRaw =
      requested && isRecord(requested) ? requested.raw : null;
    return (
      operation.planKind === "direct_external_handoff" &&
      requestedAsset != null &&
      isRawAmount(requestedRaw) &&
      input.prepared.operation.quote.planSnapshot.steps.some(
        (step) => step.normalizedAction.kind === "external_handoff",
      ) &&
      input.sealedSources.some(
        (source) =>
          source.locationId === null &&
          sameAsset(source.asset, requestedAsset) &&
          rawAmount(requestedRaw) <= rawAmount(source.maximumRaw),
      )
    );
  }
  const ownedSources = preparedOwnedSources(
    input.prepared.operation.quote.selectedSourceOptionSnapshot,
  );
  if (!ownedSources || ownedSources.length === 0) return false;
  const totals = new Map<string, bigint>();
  const maximums = new Map<string, bigint>();
  for (const debit of debits) {
    const asset = {
      assetId: debit.assetId,
      decimals: debit.assetDecimals,
      networkId: debit.networkId,
    };
    // A debit reservation must name its physical location. A null scoped
    // source is an exact external handoff and is allowed only in the zero-
    // reservation branch above; it must never authorize an arbitrary debit.
    const matchingOwnedSources = ownedSources.filter(
      (ownedSource) =>
        sameAsset(ownedSource.location.asset, asset) &&
        fundingOwnedSourceIncludesLocation(ownedSource, debit.locationId),
    );
    const reservationLocationIds = [
      ...new Set(
        matchingOwnedSources
          .map(fundingOwnedSourceReservationLocationId)
          .filter((locationId): locationId is string => locationId != null),
      ),
    ];
    if (reservationLocationIds.length !== 1) return false;
    const matchingSealedSources = input.sealedSources.filter(
      (candidate) =>
        candidate.locationId !== null &&
        sameAsset(candidate.asset, asset) &&
        matchingOwnedSources.some((ownedSource) =>
          fundingOwnedSourceIncludesLocation(
            ownedSource,
            candidate.locationId as string,
          ),
        ),
    );
    if (matchingSealedSources.length === 0) return false;
    const maximumRaw = matchingSealedSources.reduce((maximum, source) => {
      const candidate = rawAmount(source.maximumRaw);
      return candidate > maximum ? candidate : maximum;
    }, 0n);
    const key = preparedOwnedSourceKey(asset, reservationLocationIds[0]);
    totals.set(key, (totals.get(key) ?? 0n) + rawAmount(debit.rawAmount));
    maximums.set(key, maximumRaw);
  }
  return [...totals.entries()].every(
    ([key, total]) => total <= (maximums.get(key) ?? -1n),
  );
}

function preparedPlanMatchesDestinationScope(
  input: Readonly<{
    prepared: PreparedFundingRuntimeCommit;
    destination: DestinationScope;
  }>,
): boolean {
  const operation = input.prepared.operation.quote.planSnapshot.operation;
  const target = operation.destinationTargetSnapshot;
  const binding = operation.venueBindingSnapshot;
  if (!isRecord(target) || !isRecord(target.location) || !isRecord(binding)) {
    return false;
  }
  const location = target.location;
  const details = isRecord(location.details) ? location.details : null;
  const asset = exactAsset(location.asset);
  return (
    target.kind === "owned_location" &&
    operation.venueId === input.destination.venueId &&
    binding.venueBindingOptionId === input.destination.venueBindingOptionId &&
    details?.controllerWalletId === input.destination.controllerWalletId &&
    asset != null &&
    sameAsset(asset, input.destination.requiredAsset)
  );
}

function selectScopedSource(
  projection: IntentLiquidityProjection,
  sourceDebits: readonly SourceDebitScope[],
): SourceOption | null {
  return (
    projection.sourceOptions.find(
      (option) =>
        option.selectable &&
        isSealableClientFundingOption(option) &&
        telegramAppHandoffV2SourceOptionWithinScope(sourceDebits, option) &&
        option.recommended,
    ) ??
    projection.sourceOptions.find(
      (option) =>
        option.selectable &&
        isSealableClientFundingOption(option) &&
        telegramAppHandoffV2SourceOptionWithinScope(sourceDebits, option),
    ) ??
    null
  );
}

export function telegramAppHandoffV2FundingIdempotencyKey(
  handoffId: string,
): string {
  return `telegram-app-handoff:${handoffId}:funding`;
}

/**
 * The intent link is only a convenience pointer. These facts bind it to one
 * sealed v2 handoff and prevent a retry from inheriting unrelated funding.
 */
export function isTelegramAppHandoffV2FundingBinding(input: {
  handoffId: string;
  operationId: string;
  result: unknown;
}): boolean {
  if (!isRecord(input.result) || !isRecord(input.result.appHandoffFunding)) {
    return false;
  }
  const binding = input.result.appHandoffFunding;
  return (
    binding.version === 2 &&
    binding.handoffId === input.handoffId &&
    binding.operationId === input.operationId
  );
}

/**
 * Replans only inside the immutable v2 source/destination envelope. The
 * runtime remains the sole quote and operation builder; this layer supplies
 * the sealed owner boundary and verifies its output before durable commit.
 */
export async function prepareTelegramAppHandoffV2Funding(input: {
  handoffId: string;
  planSnapshot: JsonObject;
  runtime: FundingPlanningRuntime;
  tradeIntentId: string;
  userId: string;
}): Promise<PreparedFundingRuntimeCommit> {
  const plan = parseV2FundingPlan(input.planSnapshot);
  if (
    (await input.runtime.currentPolicyRevision()) !==
    plan.funding.fundingPolicyRevision
  ) {
    throw new TelegramAppHandoffV2Error(
      "funding_policy_changed",
      "funding policy changed after Telegram confirmation",
    );
  }
  // A Telegram quote expiry protects the bot-card confirmation. The sealed
  // handoff has its own TTL and re-quotes funding inside its immutable bounds,
  // so materialization must use the current funding-policy quote window.
  const currentRequest: FundingDiscoveryRequest = {
    ...plan.funding.discoveryRequest,
    deadline: null,
    destinationOptionId: plan.funding.destination.destinationOptionId,
    venueBindingOptionId: plan.funding.destination.venueBindingOptionId,
  };
  const projection = await input.runtime.liquidity(
    input.userId,
    currentRequest,
  );
  const currentDestination = projection.destinationOptions.find((option) =>
    sameDestinationScope(plan.funding.destination, option),
  );
  if (
    !currentDestination ||
    !currentDestination.selectable ||
    projection.destinationOptionId !==
      plan.funding.destination.destinationOptionId
  ) {
    throw new TelegramAppHandoffV2Error(
      "destination_changed",
      "funding destination or controller changed",
    );
  }
  const selected = selectScopedSource(projection, plan.funding.sourceDebits);
  if (!selected) {
    throw new TelegramAppHandoffV2Error(
      "source_scope_changed",
      "no current route fits the sealed source scope",
    );
  }
  const quoteRequest: FundingQuoteRequest = {
    confirmedSourceAmount: null,
    liquidityProjectionId: projection.liquidityProjectionId,
    // The sealed trade amount remains the later Buy ceiling. Funding quotes
    // cover only the exact additional destination credit still required now.
    requestedDestinationAmount:
      fundingDestinationAmountForRequest(currentRequest),
    selectedSourceOptionId: selected.sourceOptionId,
  };
  const quote = await input.runtime.quoteForCommitScope(
    input.userId,
    quoteRequest,
    {
      kind: "telegram_app_handoff_v2",
      handoffId: input.handoffId,
      tradeIntentId: input.tradeIntentId,
    },
  );
  const prepared = await input.runtime.prepareCommit(
    input.userId,
    {
      consentToken: quote.consentToken,
      idempotencyKey: telegramAppHandoffV2FundingIdempotencyKey(
        input.handoffId,
      ),
      quoteId: quote.quoteId,
    },
    {
      commitScope: {
        kind: "telegram_app_handoff_v2",
        handoffId: input.handoffId,
        tradeIntentId: input.tradeIntentId,
      },
    },
  );
  if (
    !preparedPlanWithinSourceScope({
      prepared,
      sealedSources: plan.funding.sourceDebits,
    })
  ) {
    throw new TelegramAppHandoffV2Error(
      "source_scope_changed",
      "fresh funding plan exceeds the sealed source scope",
    );
  }
  if (
    !preparedPlanMatchesDestinationScope({
      prepared,
      destination: plan.funding.destination,
    })
  ) {
    throw new TelegramAppHandoffV2Error(
      "destination_changed",
      "fresh funding plan differs from the sealed destination scope",
    );
  }
  return prepared;
}

export async function attachTelegramAppHandoffV2FundingInTransaction(
  client: PoolClient,
  input: Readonly<{
    handoffId: string;
    prepared: PreparedFundingRuntimeCommit;
    runtime: FundingPlanningRuntime;
    sealedPlan: TelegramAppHandoffV2FundingPlan;
    tradeIntentId: string;
    userId: string;
  }>,
): Promise<MaterializedTelegramAppHandoffV2> {
  const existing = await client.query<{
    action: string;
    amount_usd: string | null;
    event_id: string | null;
    funding_operation_id: string | null;
    market_id: string;
    result: unknown;
    side: string | null;
    venue: string;
  }>(
    `select intent.action,
            intent.amount_usd::text,
            intent.event_id,
            intent.funding_operation_id::text,
            intent.market_id,
            intent.result,
            intent.side,
            intent.venue
       from telegram_trade_intents intent
      where intent.id = $1::uuid
        and intent.user_id = $2::uuid
        and intent.delivery_mode = 'app_handoff'
        and intent.action = 'buy'
      for update`,
    [input.tradeIntentId, input.userId],
  );
  const intent = existing.rows[0];
  if (!intent) {
    throw new TelegramAppHandoffV2Error(
      "trade_intent_changed",
      "bound trade intent no longer belongs to this handoff",
    );
  }
  if (!sealedTradeMatchesIntent(input.sealedPlan.trade, intent)) {
    throw new TelegramAppHandoffV2Error(
      "trade_intent_changed",
      "bound trade intent differs from the sealed handoff scope",
    );
  }
  if (intent.funding_operation_id) {
    if (
      !isTelegramAppHandoffV2FundingBinding({
        handoffId: input.handoffId,
        operationId: intent.funding_operation_id,
        result: intent.result,
      })
    ) {
      throw new TelegramAppHandoffV2Error(
        "trade_intent_changed",
        "trade intent is linked to funding from a different handoff",
      );
    }
    const operation = await client.query<{ id: string }>(
      `select operation_row.id::text
         from funding_operations operation_row
        where operation_row.id = $1::uuid
          and operation_row.user_id = $2::uuid
          and operation_row.idempotency_key = $3
        for key share`,
      [
        intent.funding_operation_id,
        input.userId,
        telegramAppHandoffV2FundingIdempotencyKey(input.handoffId),
      ],
    );
    if (!operation.rows[0]) {
      throw new TelegramAppHandoffV2Error(
        "trade_intent_changed",
        "handoff funding operation no longer has its exact ownership binding",
      );
    }
    return {
      fundingOperationId: intent.funding_operation_id,
      handoffId: input.handoffId,
      kind: "client_execution_required",
      requiredContractVersion:
        TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
    };
  }
  const committed = await input.runtime.commitPreparedInTransaction(
    client,
    input.prepared,
  );
  const linked = await client.query(
    `update telegram_trade_intents intent
        set status = 'funding',
            funding_operation_id = $3::uuid,
            expires_at = greatest(
              intent.expires_at,
              clock_timestamp() + interval '30 minutes'
            ),
            result = coalesce(intent.result, '{}'::jsonb) || jsonb_build_object(
              'appHandoffFunding',
              jsonb_build_object(
                'handoffId', $4::uuid,
                'operationId', $3::uuid,
                'version', 2
              )
            ),
            updated_at = clock_timestamp()
      where intent.id = $1::uuid
        and intent.user_id = $2::uuid
        and intent.delivery_mode = 'app_handoff'
        and intent.action = 'buy'
        and intent.funding_operation_id is null
        and intent.status in ('previewed', 'confirming', 'external_handoff')`,
    [
      input.tradeIntentId,
      input.userId,
      committed.operation.id,
      input.handoffId,
    ],
  );
  if ((linked.rowCount ?? 0) !== 1) {
    throw new TelegramAppHandoffV2Error(
      "trade_intent_changed",
      "trade intent changed while attaching funding operation",
    );
  }
  return {
    fundingOperationId: committed.operation.id,
    handoffId: input.handoffId,
    kind: "client_execution_required",
    requiredContractVersion: TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
  };
}

async function assertTelegramAppHandoffV2DirectTradeInTransaction(input: {
  client: PoolClient;
  sealedPlan: TelegramAppHandoffV2DirectTradePlan;
  tradeIntentId: string;
  userId: string;
}): Promise<void> {
  const { rows } = await input.client.query<{
    action: string;
    amount_usd: string | null;
    event_id: string | null;
    market_id: string;
    shares_raw: string | null;
    side: string | null;
    status: string;
    venue: string;
  }>(
    `select intent.action,
            intent.amount_usd::text,
            intent.event_id,
            intent.market_id,
            intent.shares_raw,
            intent.side,
            intent.status,
            intent.venue
       from telegram_trade_intents intent
      where intent.id = $1::uuid
        and intent.user_id = $2::uuid
        and intent.delivery_mode = 'app_handoff'
        and intent.action in ('buy', 'sell')
      for update`,
    [input.tradeIntentId, input.userId],
  );
  if (
    !rows[0] ||
    !["previewed", "confirming", "external_handoff"].includes(rows[0].status) ||
    !sealedTradeMatchesIntent(input.sealedPlan.trade, rows[0])
  ) {
    throw new TelegramAppHandoffV2Error(
      "trade_intent_changed",
      "bound direct trade differs from the sealed handoff scope",
    );
  }
}

async function loadAttachedTelegramAppHandoffV2Funding(input: {
  db: Pool;
  handoffId: string;
  tradeIntentId: string;
  userId: string;
}): Promise<MaterializedTelegramAppHandoffV2 | null> {
  const { rows } = await input.db.query<{
    funding_operation_id: string | null;
  }>(
    `select intent.funding_operation_id::text
       from telegram_trade_intents intent
       join funding_operations operation_row
         on operation_row.id = intent.funding_operation_id
        and operation_row.user_id = intent.user_id
      where intent.id = $1::uuid
        and intent.user_id = $2::uuid
        and intent.delivery_mode = 'app_handoff'
        and intent.action = 'buy'
        and intent.result -> 'appHandoffFunding' ->> 'version' = '2'
        and intent.result -> 'appHandoffFunding' ->> 'handoffId' = $3::text
        and intent.result -> 'appHandoffFunding' ->> 'operationId' = intent.funding_operation_id::text
        and operation_row.idempotency_key = $4
      limit 1`,
    [
      input.tradeIntentId,
      input.userId,
      input.handoffId,
      telegramAppHandoffV2FundingIdempotencyKey(input.handoffId),
    ],
  );
  const operationId = rows[0]?.funding_operation_id;
  return operationId
    ? {
        fundingOperationId: operationId,
        handoffId: input.handoffId,
        kind: "client_execution_required",
        requiredContractVersion:
          TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
      }
    : null;
}

function tradeConsumerMatchesSealedPlan(input: {
  plan: TelegramAppHandoffV2FundingPlan;
  reservation: Awaited<
    ReturnType<typeof fetchFundingConsumerReservationForUser>
  >;
}): boolean {
  const consumer = input.plan.funding.discoveryRequest.consumerIntent;
  const reservationConsumer = input.reservation?.consumerIntent;
  return (
    consumer != null &&
    reservationConsumer != null &&
    consumer.venueId === reservationConsumer.venueId &&
    consumer.marketId === reservationConsumer.marketId &&
    consumer.marketContextId === reservationConsumer.marketContextId &&
    consumer.side === reservationConsumer.side &&
    sameAsset(consumer.spend.asset, reservationConsumer.spend.asset) &&
    consumer.spend.raw === reservationConsumer.spend.raw
  );
}

async function resolveReadyTelegramAppHandoffV2TradeContinuation(input: {
  db: Pool;
  handoff: TelegramAppHandoff;
  plan: TelegramAppHandoffV2FundingPlan;
  userId: string;
}): Promise<TelegramAppHandoffV2TradeContinuation | null> {
  return tx(input.db, async (client) => {
    const intentResult = await client.query<{
      funding_operation_id: string | null;
      funding_reservation_id: string | null;
      status: string;
    }>(
      `select intent.funding_operation_id::text,
              intent.funding_reservation_id::text,
              intent.status
         from telegram_trade_intents intent
        where intent.id = $1::uuid
          and intent.user_id = $2::uuid
          and intent.delivery_mode = 'app_handoff'
          and intent.action = 'buy'
        for update`,
      [input.handoff.tradeIntentId, input.userId],
    );
    const intent = intentResult.rows[0];
    if (!intent?.funding_operation_id) return null;
    const reservation = await fetchFundingConsumerReservationForUser(client, {
      forUpdate: true,
      operationId: intent.funding_operation_id,
      userId: input.userId,
    });
    if (!reservation) return null;
    if (!tradeConsumerMatchesSealedPlan({ plan: input.plan, reservation })) {
      throw new TelegramAppHandoffV2Error(
        "trade_intent_changed",
        "ready funding does not match the sealed trade bounds",
      );
    }
    if (
      intent.funding_reservation_id != null &&
      intent.funding_reservation_id !== reservation.reservationId
    ) {
      throw new TelegramAppHandoffV2Error(
        "trade_intent_changed",
        "trade intent is already linked to a different funding reservation",
      );
    }
    if (intent.funding_reservation_id == null) {
      const attached = await client.query(
        `update telegram_trade_intents intent
            set funding_reservation_id = $2::uuid,
                result = coalesce(intent.result, '{}'::jsonb) || jsonb_build_object(
                  'appHandoffFundingReady', jsonb_build_object(
                    'handoffId', $3::uuid,
                    'operationId', $4::uuid,
                    'reservationId', $2::uuid,
                    'version', 2
                  )
                ),
                updated_at = clock_timestamp()
          where intent.id = $1::uuid
            and intent.status = 'funding'
            and intent.funding_operation_id = $4::uuid
            and intent.funding_reservation_id is null`,
        [
          input.handoff.tradeIntentId,
          reservation.reservationId,
          input.handoff.id,
          reservation.operationId,
        ],
      );
      if ((attached.rowCount ?? 0) !== 1) {
        throw new TelegramAppHandoffV2Error(
          "trade_intent_changed",
          "trade intent changed while linking ready funding",
        );
      }
    }
    return {
      fundingOperationId: reservation.operationId,
      fundingReservationId: reservation.reservationId,
      handoffId: input.handoff.id,
      kind: "trade_continuation_required",
      requiredContractVersion:
        TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
    };
  });
}

async function resolveTelegramAppHandoffV2TradeTerminal(input: {
  db: Pool;
  handoff: TelegramAppHandoff;
  userId: string;
}): Promise<TelegramAppHandoffV2TradeTerminal | null> {
  const { rows } = await input.db.query<{ status: string }>(
    `select intent.status
       from telegram_trade_intents intent
      where intent.id = $1::uuid
        and intent.user_id = $2::uuid
        and intent.delivery_mode = 'app_handoff'
        and intent.action in ('buy', 'sell')
      limit 1`,
    [input.handoff.tradeIntentId, input.userId],
  );
  const status = rows[0]?.status;
  if (
    status !== "filled" &&
    status !== "failed" &&
    status !== "cancelled" &&
    status !== "expired"
  ) {
    return null;
  }
  return {
    handoffId: input.handoff.id,
    kind: "trade_terminal",
    requiredContractVersion: TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
    status,
    tradeIntentId: input.handoff.tradeIntentId,
  };
}

async function resolveTelegramAppHandoffV2TradeInFlight(input: {
  db: Pool;
  handoff: TelegramAppHandoff;
  userId: string;
}): Promise<TelegramAppHandoffV2TradeInFlight | null> {
  const { rows } = await input.db.query<{
    attempt_id: string;
    attempt_state: "accepted" | "ambiguous" | "claimed" | "submission_started";
    funding_operation_id: string;
    funding_reservation_id: string;
  }>(
    `select attempt.id::text as attempt_id,
            attempt.state as attempt_state,
            intent.funding_operation_id::text,
            intent.funding_reservation_id::text
       from telegram_trade_intents intent
       join funding_trade_attempts attempt
         on attempt.user_id = intent.user_id
        and attempt.operation_id = intent.funding_operation_id
        and attempt.reservation_id = intent.funding_reservation_id
      where intent.id = $1::uuid
        and intent.user_id = $2::uuid
        and intent.delivery_mode = 'app_handoff'
        and intent.action = 'buy'
        and intent.result -> 'appHandoffFunding' ->> 'version' = '2'
        and intent.result -> 'appHandoffTradeExecution' ->> 'version' = '2'
        and intent.result -> 'appHandoffTradeExecution' ->> 'attemptId'
          = attempt.id::text
        and attempt.state in (
          'claimed',
          'submission_started',
          'ambiguous',
          'accepted'
        )
      order by attempt.attempt_number desc
      limit 1`,
    [input.handoff.tradeIntentId, input.userId],
  );
  const row = rows[0];
  if (!row) return null;
  return {
    fundingOperationId: row.funding_operation_id,
    fundingReservationId: row.funding_reservation_id,
    handoffId: input.handoff.id,
    kind: "trade_continuation_in_flight",
    requiredContractVersion: TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
    tradeAttemptId: row.attempt_id,
    tradeAttemptState: row.attempt_state,
  };
}

/**
 * Read-only v2 execution lookup. This intentionally cannot create or commit
 * funding: only the explicit `/commit` endpoint may cross that boundary.
 */
export async function resolveTelegramAppHandoffV2Execution(input: {
  db: Pool;
  handoff: TelegramAppHandoff;
  userId: string;
}): Promise<TelegramAppHandoffV2Execution> {
  const plan = parseV2Plan(input.handoff.planSnapshot);
  const terminal = await resolveTelegramAppHandoffV2TradeTerminal({
    db: input.db,
    handoff: input.handoff,
    userId: input.userId,
  });
  if (terminal) return terminal;
  if (input.handoff.state !== "committed") {
    throw new TelegramAppHandoffV2Error(
      "handoff_not_committed",
      "funding must be committed before client actions can be prepared",
    );
  }
  if (plan.kind === "direct_trade") {
    const intent = await input.db.query<{
      action: string;
      amount_usd: string | null;
      event_id: string | null;
      market_id: string;
      order_id: string | null;
      side: string | null;
      shares_raw: string | null;
      status: string;
      venue: string;
      venue_order_id: string | null;
    }>(
      `select intent.action,
              intent.amount_usd::text,
              intent.event_id,
              intent.market_id,
              intent.order_id::text,
              intent.side,
              intent.shares_raw,
              intent.status,
              intent.venue,
              intent.venue_order_id
         from telegram_trade_intents intent
        where intent.id = $1::uuid
          and intent.user_id = $2::uuid
          and intent.delivery_mode = 'app_handoff'
          and intent.action in ('buy', 'sell')`,
      [input.handoff.tradeIntentId, input.userId],
    );
    const directIntent = intent.rows[0];
    if (!directIntent || !sealedTradeMatchesIntent(plan.trade, directIntent)) {
      throw new TelegramAppHandoffV2Error(
        "trade_intent_changed",
        "bound direct trade is no longer awaiting the sealed continuation",
      );
    }
    if (
      ["executing", "submitted", "reconcile_required"].includes(
        directIntent.status,
      )
    ) {
      return {
        handoffId: input.handoff.id,
        kind: "direct_trade_in_flight",
        orderId: directIntent.order_id,
        planFingerprint: input.handoff.planFingerprint,
        requiredContractVersion:
          TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
        tradeIntentId: input.handoff.tradeIntentId,
        venueOrderId: directIntent.venue_order_id,
      };
    }
    if (directIntent.status !== "external_handoff") {
      throw new TelegramAppHandoffV2Error(
        "trade_intent_changed",
        "bound direct trade is no longer awaiting the sealed continuation",
      );
    }
    return {
      handoffId: input.handoff.id,
      kind: "direct_trade_continuation_required",
      planFingerprint: input.handoff.planFingerprint,
      requiredContractVersion:
        TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
      tradeIntentId: input.handoff.tradeIntentId,
    };
  }
  const existing = await loadAttachedTelegramAppHandoffV2Funding({
    db: input.db,
    handoffId: input.handoff.id,
    tradeIntentId: input.handoff.tradeIntentId,
    userId: input.userId,
  });
  if (!existing) {
    throw new TelegramAppHandoffV2Error(
      "handoff_not_committed",
      "committed handoff has no attached funding operation",
    );
  }
  const inFlight = await resolveTelegramAppHandoffV2TradeInFlight({
    db: input.db,
    handoff: input.handoff,
    userId: input.userId,
  });
  if (inFlight) return inFlight;
  return (
    (await resolveReadyTelegramAppHandoffV2TradeContinuation({
      db: input.db,
      handoff: input.handoff,
      plan,
      userId: input.userId,
    })) ?? existing
  );
}

/**
 * Claim/commit entrypoint for a v2 Mini App consumer. It is deliberately the
 * only code path that can materialize a sealed funding plan from a th1_ token
 * or release the sealed direct-Buy continuation to its web consumer.
 */
export async function materializeTelegramAppHandoffV2Funding(input: {
  currentAuthorityFingerprint: string;
  currentPolicyRevision: string;
  db: Pool;
  planFingerprint: string;
  runtime: FundingPlanningRuntime;
  telegramUserId: string;
  token: string;
  userId: string;
}): Promise<
  Readonly<{
    execution:
      | MaterializedTelegramAppHandoffV2
      | TelegramAppHandoffV2DirectTradeContinuation;
    handoff: TelegramAppHandoff;
  }>
> {
  // A second Mini App tab can commit between the route-level resolve and this
  // function. Reload before returning so an idempotent response never pairs
  // an existing operation with stale `claimed` handoff state.
  const handoff = await resolveTelegramAppHandoff({
    db: input.db,
    telegramUserId: input.telegramUserId,
    token: input.token,
    userId: input.userId,
  });
  const sealedPlan = parseV2Plan(handoff.planSnapshot);
  if (handoff.state !== "claimed" && handoff.state !== "committed") {
    throw new TelegramAppHandoffV2Error(
      "handoff_not_claimed",
      "handoff must be claimed by the bound Mini App before continuation starts",
    );
  }
  if (input.planFingerprint.trim().toLowerCase() !== handoff.planFingerprint) {
    throw new TelegramAppHandoffV2Error(
      "plan_invalid",
      "sealed handoff plan changed before funding commit",
    );
  }
  if (
    input.currentPolicyRevision !== handoff.policyRevision ||
    input.currentAuthorityFingerprint.trim().toLowerCase() !==
      handoff.authorityFingerprint
  ) {
    throw new TelegramAppHandoffV2Error(
      "funding_policy_changed",
      "wallet authority or policy changed after Telegram confirmation",
    );
  }
  if (sealedPlan.kind === "direct_trade") {
    return commitTelegramAppHandoffWithExecution({
      commitExecution: async ({ client }) => {
        await assertTelegramAppHandoffV2DirectTradeInTransaction({
          client,
          sealedPlan,
          tradeIntentId: handoff.tradeIntentId,
          userId: input.userId,
        });
        return {
          handoffId: handoff.id,
          kind: "direct_trade_continuation_required" as const,
          planFingerprint: handoff.planFingerprint,
          requiredContractVersion:
            TELEGRAM_APP_HANDOFF_V2_EXECUTION_CONTRACT_VERSION,
          tradeIntentId: handoff.tradeIntentId,
        };
      },
      committedIntentStatus: "external_handoff",
      executionKind: "direct_trade",
      allowedIntentActions: [
        sealedPlan.trade.action === "sell" ? "sell" : "buy",
      ],
      allowedIntentStatuses: ["previewed", "confirming", "external_handoff"],
      currentAuthorityFingerprint: input.currentAuthorityFingerprint,
      currentPolicyRevision: input.currentPolicyRevision,
      db: input.db,
      planFingerprint: input.planFingerprint,
      telegramUserId: input.telegramUserId,
      token: input.token,
      userId: input.userId,
    });
  }
  const existing = await loadAttachedTelegramAppHandoffV2Funding({
    db: input.db,
    handoffId: handoff.id,
    tradeIntentId: handoff.tradeIntentId,
    userId: input.userId,
  });
  const commitFundingExecution = (
    commitExecution: (
      context: Readonly<{ client: PoolClient }>,
    ) => Promise<MaterializedTelegramAppHandoffV2>,
  ) =>
    commitTelegramAppHandoffWithExecution({
      allowedIntentStatuses: ["funding"],
      commitExecution,
      currentAuthorityFingerprint: input.currentAuthorityFingerprint,
      executionKind: "funding",
      currentPolicyRevision: input.currentPolicyRevision,
      db: input.db,
      planFingerprint: input.planFingerprint,
      telegramUserId: input.telegramUserId,
      token: input.token,
      userId: input.userId,
    });
  if (existing) {
    // Retries still pass through the common commit boundary. Besides keeping
    // the handoff idempotent, this repairs intents created before that boundary
    // started clearing the obsolete `external_handoff_required` marker.
    return commitFundingExecution(async () => existing);
  }
  const prepared = await prepareTelegramAppHandoffV2Funding({
    handoffId: handoff.id,
    planSnapshot: handoff.planSnapshot,
    runtime: input.runtime,
    tradeIntentId: handoff.tradeIntentId,
    userId: input.userId,
  });
  return commitFundingExecution(({ client }) =>
    attachTelegramAppHandoffV2FundingInTransaction(client, {
      handoffId: handoff.id,
      prepared,
      runtime: input.runtime,
      sealedPlan,
      tradeIntentId: handoff.tradeIntentId,
      userId: input.userId,
    }),
  );
}

/** Used by tests and callers to assert the exact public v2 action surface. */
export function telegramAppHandoffV2SupportsActionKind(kind: string): boolean {
  return SUPPORTED_CLIENT_ACTION_KINDS.has(
    kind as typeof SUPPORTED_CLIENT_ACTION_KINDS extends Set<infer T>
      ? T
      : never,
  );
}
