import type { FastifyInstance } from "fastify";
import { authRoutes } from "./auth.js";
import { bridgeRoutes } from "./bridge.js";
import { dflowPrivateRoutes } from "./dflow-private.js";
import { adminRoutes } from "./admin.js";
import { eventRoutes } from "./events.js";
import { executionsRoutes } from "./executions.js";
import { feesRoutes } from "./fees.js";
import { feedRoutes } from "./feed.js";
import { healthRoutes } from "./health.js";
import { holdersRoutes } from "./holders.js";
import { marketRoutes } from "./markets.js";
import { metaRoutes } from "./meta.js";
import { metricsRoutes } from "./metrics.js";
import { ordersRoutes } from "./orders.js";
import { positionsRoutes } from "./positions.js";
import { pricesSseRoutes } from "./prices-sse.js";
import { tradesRoutes } from "./trades.js";
import { limitlessPrivateRoutes } from "./limitless-private.js";
import { polymarketPrivateRoutes } from "./polymarket-private.js";
import { polymarketProxyRoutes } from "./polymarket-proxy.js";
import { rewardsRoutes } from "./rewards.js";
import { solanaRoutes } from "./solana.js";
import { tradePolicyRoutes } from "./trade-policies.js";
import { walletsRoutes } from "./wallets.js";
import { watchlistRoutes } from "./watchlist.js";

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await app.register(metricsRoutes);
  await app.register(healthRoutes);
  await app.register(metaRoutes);
  await app.register(tradePolicyRoutes);
  await app.register(adminRoutes);
  await app.register(feesRoutes);
  await app.register(bridgeRoutes);
  await app.register(authRoutes);
  await app.register(polymarketPrivateRoutes, { prefix: "/trade/polymarket" });
  await app.register(limitlessPrivateRoutes, { prefix: "/trade/limitless" });
  await app.register(dflowPrivateRoutes, { prefix: "/trade/kalshi" });
  await app.register(dflowPrivateRoutes, { prefix: "/trade/dflow" });
  await app.register(polymarketProxyRoutes);
  await app.register(solanaRoutes);
  await app.register(pricesSseRoutes);
  await app.register(feedRoutes);
  await app.register(holdersRoutes);
  await app.register(marketRoutes);
  await app.register(eventRoutes);
  await app.register(executionsRoutes);
  await app.register(ordersRoutes);
  await app.register(tradesRoutes);
  await app.register(rewardsRoutes);
  await app.register(positionsRoutes);
  await app.register(walletsRoutes);
  await app.register(watchlistRoutes);
}
