export const DELEGATED_PROVIDER_RECOVERY_MS = 5 * 60_000;
export const DELEGATED_PROVIDER_EVIDENCE_RECOVERY_MS = 15_000;
export const DELEGATED_PROVIDER_EVIDENCE_RECOVERY_CLAIM_KEY =
  "providerEvidenceRecoveryClaimedAt";
