#!/usr/bin/env tsx

import { getAssociatedTokenAddressSync } from "@solana/spl-token";
import { Keypair, PublicKey } from "@solana/web3.js";
import bs58 from "bs58";
import { Wallet } from "ethers";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const DEFAULT_SOLANA_USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
const DEFAULT_POLYGON_USDC = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174";
const DEFAULT_BASE_USDC = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913";
const DEFAULT_POLYMARKET_EXCHANGE = "0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E";
const DEFAULT_POLYMARKET_NEG_RISK_EXCHANGE =
  "0xC5d563A36AE78145C45a50134d48A1215220f80a";

type CliOptions = {
  outJsonPath?: string;
  outEnvPath?: string;
  solanaUsdcMint: string;
};

type EvmWallet = {
  address: string;
  privateKey: string;
};

type SolanaWallet = {
  address: string;
  secretKeyBs58: string;
  secretKeyArray: number[];
};

function parseArgs(args: string[]): CliOptions {
  const getValue = (flag: string): string | undefined => {
    const idx = args.indexOf(flag);
    if (idx === -1) return undefined;
    const next = args[idx + 1];
    return next && !next.startsWith("--") ? next : undefined;
  };

  const solanaUsdcMint = getValue("--solana-usdc-mint") ?? DEFAULT_SOLANA_USDC_MINT;
  const outJsonPath = getValue("--out-json");
  const outEnvPath = getValue("--out-env");

  return {
    outJsonPath: outJsonPath?.trim() || undefined,
    outEnvPath: outEnvPath?.trim() || undefined,
    solanaUsdcMint: solanaUsdcMint.trim(),
  };
}

function printHelp() {
  console.log(`
Generate production wallet material for rewards + fees.
Creates 2 hot keys by default:
  - 1 EVM key (shared for collector + payouts)
  - 1 Solana key

Usage:
  pnpm -C hunch-monorepo -F api run rewards:wallets:generate [options]

Options:
  --solana-usdc-mint <mint>   Solana USDC mint used to derive DFlow fee account
                              (default: ${DEFAULT_SOLANA_USDC_MINT})
  --out-json <path>           Write full JSON output to file
  --out-env <path>            Write .env snippet output to file
  --help                      Show this help
`);
}

function createEvmWallet(): EvmWallet {
  const wallet = Wallet.createRandom();
  return {
    address: wallet.address,
    privateKey: wallet.privateKey,
  };
}

function createSolanaWallet(): SolanaWallet {
  const keypair = Keypair.generate();
  return {
    address: keypair.publicKey.toBase58(),
    secretKeyBs58: bs58.encode(keypair.secretKey),
    secretKeyArray: Array.from(keypair.secretKey),
  };
}

function renderEnvSnippet(inputs: {
  feeCollectorContractAddressPlaceholder: string;
  evmHot: EvmWallet;
  rewardsHotSolana: SolanaWallet;
  dflowFeeAccount: string;
  debridgeAffiliateFeeRecipients: string;
}): string {
  const lines: string[] = [
    "# === Rewards / Fees wallet material (generated) ===",
    "# Keep this file secret. Do NOT commit.",
    "",
    "# Fee collector contract (set after deploy)",
    `HUNCH_FEE_COLLECTOR_ADDRESS=${inputs.feeCollectorContractAddressPlaceholder}`,
    "",
    "# Shared EVM hot key (collector operator + rewards payouts)",
    `HUNCH_FEE_COLLECTOR_PRIVATE_KEY=${inputs.evmHot.privateKey}`,
    `HUNCH_REWARDS_PAYOUT_PRIVATE_KEY=${inputs.evmHot.privateKey}`,
    "",
    "# Rewards payout hot wallets",
    `HUNCH_REWARDS_PAYOUT_PRIVATE_KEY_POLYGON=${inputs.evmHot.privateKey}`,
    `HUNCH_REWARDS_PAYOUT_PRIVATE_KEY_BASE=${inputs.evmHot.privateKey}`,
    `HUNCH_REWARDS_SOLANA_SECRET_KEY=${inputs.rewardsHotSolana.secretKeyBs58}`,
    "",
    "# Rewards payout token addresses",
    `HUNCH_REWARDS_USDC_ADDRESS_POLYGON=${DEFAULT_POLYGON_USDC}`,
    `HUNCH_REWARDS_USDC_ADDRESS_BASE=${DEFAULT_BASE_USDC}`,
    "",
    "# Treasury cold addresses (set manually, not generated by this script)",
    "HUNCH_REWARDS_TREASURY_COLD_ADDRESS_POLYGON=",
    "HUNCH_REWARDS_TREASURY_COLD_ADDRESS_BASE=",
    "HUNCH_REWARDS_TREASURY_COLD_ADDRESS_SOLANA=",
    "",
    "# DFlow fee receiving token account (USDC ATA owned by rewards hot Solana wallet)",
    `DFLOW_USDC_FEE_ACCOUNT=${inputs.dflowFeeAccount}`,
    "",
    "# Optional but recommended explicit USDC mint for DFlow/Kalshi",
    `DFLOW_USDC_MINT=${DEFAULT_SOLANA_USDC_MINT}`,
    "",
    "# Bridge affiliate fee recipients (Polygon/Base use EVM hot; Solana uses hot Solana wallet)",
    `DEBRIDGE_AFFILIATE_FEE_RECIPIENTS=${inputs.debridgeAffiliateFeeRecipients}`,
    "",
  ];
  return lines.join("\n");
}

function writeText(pathValue: string, content: string) {
  const abs = resolve(pathValue);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content, "utf8");
  return abs;
}

async function main() {
  const args = process.argv.slice(2);
  if (args.includes("--help")) {
    printHelp();
    return;
  }

  const options = parseArgs(args);
  const parsedMint = new PublicKey(options.solanaUsdcMint);

  const evmHot = createEvmWallet();
  const rewardsHotSolana = createSolanaWallet();

  const dflowFeeAccount = getAssociatedTokenAddressSync(
    parsedMint,
    new PublicKey(rewardsHotSolana.address),
    false,
  ).toBase58();
  const debridgeAffiliateFeeRecipients = JSON.stringify({
    "137": evmHot.address,
    "8453": evmHot.address,
    "7565164": rewardsHotSolana.address,
  });

  const feeCollectorContractAddressPlaceholder = "__SET_AFTER_DEPLOY__";

  const envSnippet = renderEnvSnippet({
    feeCollectorContractAddressPlaceholder,
    evmHot,
    rewardsHotSolana,
    dflowFeeAccount,
    debridgeAffiliateFeeRecipients,
  });

  const output = {
    generatedAt: new Date().toISOString(),
    networks: {
      polygon: {
        feeCollectorOperatorAddress: evmHot.address,
        rewardsHotAddress: evmHot.address,
        usdcAddress: DEFAULT_POLYGON_USDC,
        exchangeAddress: DEFAULT_POLYMARKET_EXCHANGE,
        negRiskExchangeAddress: DEFAULT_POLYMARKET_NEG_RISK_EXCHANGE,
      },
      base: {
        rewardsHotAddress: evmHot.address,
        usdcAddress: DEFAULT_BASE_USDC,
      },
      solana: {
        rewardsHotAddress: rewardsHotSolana.address,
        usdcMint: options.solanaUsdcMint,
        dflowFeeAccount,
      },
    },
    secrets: {
      evmHotPrivateKey: evmHot.privateKey,
      rewardsSolanaSecretKeyBs58: rewardsHotSolana.secretKeyBs58,
      rewardsSolanaSecretKeyArray: rewardsHotSolana.secretKeyArray,
    },
    envSnippet,
    deploy: {
      feeCollectorV2Command:
        `pnpm -C hunch-monorepo/packages/contracts deploy -- --network polygon ` +
        `--treasury ${evmHot.address} ` +
        `--collateral ${DEFAULT_POLYGON_USDC} ` +
        `--exchange ${DEFAULT_POLYMARKET_EXCHANGE} ` +
        `--negRiskExchange ${DEFAULT_POLYMARKET_NEG_RISK_EXCHANGE}`,
      reminder:
        "After deploy: set HUNCH_FEE_COLLECTOR_ADDRESS to deployed contract address.",
    },
  };

  console.log("Generated wallet set for rewards + fee collection.");
  console.log("");
  console.log("Public addresses:");
  console.log(`- evmHot (collector+payout):      ${evmHot.address}`);
  console.log(`- rewardsHot (solana):            ${rewardsHotSolana.address}`);
  console.log(`- dflowFeeAccount (solana ATA):   ${dflowFeeAccount}`);
  console.log("");
  console.log("Deploy fee collector:");
  console.log(output.deploy.feeCollectorV2Command);
  console.log("");
  console.log(envSnippet);

  if (options.outJsonPath) {
    const abs = writeText(options.outJsonPath, `${JSON.stringify(output, null, 2)}\n`);
    console.log(`\nWrote JSON output: ${abs}`);
  }
  if (options.outEnvPath) {
    const abs = writeText(options.outEnvPath, `${envSnippet}\n`);
    console.log(`Wrote env snippet: ${abs}`);
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
