# ops/Dockerfile.ts-toolkit

FROM timescale/timescaledb:2.14.2-pg16-bullseye

USER root
RUN apt-get update \
  && apt-get install -y timescaledb-toolkit \
  && rm -rf /var/lib/apt/lists/*

USER postgres
