export const FUNDING_RECEIVE_SESSION_TTL_HOURS = 24;

export const FUNDING_RECEIVE_SESSION_TTL_MS =
  FUNDING_RECEIVE_SESSION_TTL_HOURS * 60 * 60 * 1_000;

export const FUNDING_RECEIVE_OBSERVATION_GRACE_DAYS = 7;

export const FUNDING_RECEIVE_OBSERVATION_GRACE_MS =
  FUNDING_RECEIVE_OBSERVATION_GRACE_DAYS * 24 * 60 * 60 * 1_000;
